services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - '3000:3000'
    environment:
      RABBIT_MQ_URI: amqp://rabbitmq:5672

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBIT_MQ_URI: amqp://rabbitmq:5672
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: x-ray
      MONGO_USERNAME: root
      MONGO_PASSWORD: my-secret-pw

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Management UI
    restart: unless-stopped

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my-secret-pw
      MONGO_INITDB_DATABASE: x-ray
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
